### ISSUE TITLE
Synchronize sampling with external clock

### ISSUE THREAD

**Issue by gnsssdr** [merbanan/sigrok-firmware-fx2lafw#2]
Hello merbanan
Is there any posibility to synchronize samples with external clock? Shoud i change the firmware to achieve this?

**Comment by merbanan** [comment]
You have to look into the reference manual to see if it is possible.

https://www.infineon.com/dgdl/Infineon-EZ-USB_TECHNICAL_REFERENCE_MANUAL-AdditionalTechnicalInformation-v08_00-EN.pdf?fileId=8ac78c8c7d0d8da4017d0f9093657d61&utm_source=cypress&utm_medium=referral&utm_campaign=202110_globe_en_all_integration-technical_reference_manual

page 21 indicates that it might be possible.
